name: Update AI News Dashboard (hourly)

on:
  schedule:
    - cron: "0 * * * *"   # 매 정각마다
  workflow_dispatch: {}    # 수동 실행 버튼

jobs:
  update:
    runs-on: ubuntu-latest

    concurrency:
      group: ai-news-dashboard-hourly
      cancel-in-progress: false

    permissions:
      contents: write   # 커밋/푸시 권한

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install yfinance feedparser requests pytz

      - name: Run updater
        env:
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}   # 선택(없어도 됨)
        run: python scripts/update_dashboard.py

      - name: Commit & Push changes (only if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No data changes."
          else
            git commit -m "auto: hourly refresh"
            git push
          fi
          heads = collect_headlines()
print(f" - collected headlines: {len(heads)}")   # ✅ 추가
save_json(os.path.join(DATA, "headlines.json"), heads[:50])
print(" - headlines.json updated")
